### ISSUE TITLE
Pyinstaller build fails

### ISSUE THREAD

**Issue by augasur** [ParisNeo/QPanda3D#13]
Hi,
love the library, but I have encountered the problem if I try to build buttons_example.py to EXE with PyInstaller. Here is Traceback which we got when trying to launch built EXE.

```
Warning: unable to auto-locate config files in directory named by "<auto>etc".
Known pipe types:
(all display modules loaded.)
Traceback (most recent call last):
  File "buttons_example.py", line 74, in <module>
  File "buttons_example.py", line 25, in __init__
  File "QPanda3D\Panda3DWorld.py", line 51, in __init__
  File "direct\showbase\ShowBase.py", line 339, in __init__
  File "direct\showbase\ShowBase.py", line 1021, in openDefaultWindow
  File "direct\showbase\ShowBase.py", line 1056, in openMainWindow
  File "direct\showbase\ShowBase.py", line 766, in openWindow
  File "direct\showbase\ShowBase.py", line 752, in <lambda>
  File "direct\showbase\ShowBase.py", line 818, in _doOpenWindow
  File "direct\showbase\ShowBase.py", line 648, in makeDefaultPipe
  File "direct\directnotify\Notifier.py", line 130, in error
Exception: No graphics pipe is available!
Your Config.prc file must name at least one valid panda display
library via load-display or aux-display.
[4484] Failed to execute script buttons_example
```

Here is my run.spec file: 

```
block_cipher = None

import importlib
from pathlib import Path

package_imports = [['qtmodern', ['resources/frameless.qss', 'resources/style.qss']]]

added_file = []
for package, files in package_imports:
    proot = Path(importlib.import_module(package).__file__).parent
    added_file.extend((proot / f, package) for f in files)
added_file.append(('D:\\Anaconda\\envs\\python_opengl\\Lib\\site-packages\\PyQt5\\Qt5\\bin\*', 'PyQt5\\Qt\\bin'))


a = Analysis(['buttons_example.py'],
             pathex=['D:\\Projektai\\METOD_robotai\\Source\\ProductData\\panda_test',
			 'D:\\Anaconda\\envs\\python_opengl\\Lib\\site-packages'],
             binaries=[],
             datas=added_file,
             hiddenimports=['panda3d',
                            'PyQt5',
                            'numpy',
                            'QPanda3D',
                            'openal',
                            'pygame'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='run',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='run')
```

Stack: 

- conda 4.7.11
- Windows 10
- Python 3.6.9
- pyinstaller==4.3
- PyQt5==5.15.4
- QPanda3D==0.2.7

**Comment by ParisNeo** [comment]
Ah, yeah.. Py installer is sometimes a pain in the a**. I didn't bundle code with this library yet. As it is still in GPL licence (because of PyQt), which means that any thing written using this library must be opensource. So converting to exe was not a priority.

But I'm seriously thinking to change the licence to MIT to allow people to use this part as opensource in non opensource apps.
GPL is so contaminating.
But the only way to do this is to move to PySide2 which is LGPL allowing us to have a different licence.


So back to PyInstaller. I'll try to do this tomorrow as it is getting late here in France and I've got to go to sleep.

Thanks for bringing this issue to my attention.

**Comment by ParisNeo** [comment]
This problem was fixed today by adding a new hook to be used by pyinstaller in order to build your app.
This hook can also be used for panda3d apps (without QPanda3d).

I added all needed instructions to the doc folder of this repository.

Thanks for your comment.
